---
name: Release Terraform
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
      release-message:
        required: true

jobs:
  release-terraform:
    if: github.event.ref == 'refs/heads/main'
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-terraform.yaml@main  
    with:
      module-name: vsphere-vm
      tag-name: ${{ github.event.inputs.release-tag }}
      release-message: ${{ github.event.inputs.release-message }}
      environment-name: k8s
      runs-on: arc-runner-scale-set-vsphere-vm
      continue-error: false
