---
name: Validate and Release Terraform Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string
      github-runner:
        required: false
        type: string
        default: ghr-vsphere-vm-cicd
      environment-name:
        required: false
        type: string
        default: k8s
        
jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main  
    with:
      environment-name: "${{ github.event.inputs.environment-name }}"
      runs-on: "${{ github.event.inputs.github-runner }}"
      terraform-version: 1.7.5
      tflint-version: v0.50.3
      continue-error: false

  release-terraform:
    name: Release
    needs: validate-terraform
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-release-module.yaml@main  
    with:
      module-name: vsphere-vm
      archive-kind: zip
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: "${{ github.event.inputs.environment-name }}"
      runs-on: "${{ github.event.inputs.github-runner }}"
      continue-error: false
