---
name: Validate and Release Terraform Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string

jobs:
  Validate-Terraform:
    if: github.event.ref == 'refs/heads/main'
    name: Validate
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-validate-terraform.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-vsphere-vm-in-cluster
      terraform-version: 1.10.5
      tflint-version: v0.55.1
      continue-error: false

  Release-Terraform:
    if: github.event.ref == 'refs/heads/main'
    name: Release
    needs: Validate-Terraform
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-release-module.yaml@main
    with:
      module-name: vsphere-vm
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      runs-on: ghr-vsphere-vm-in-cluster
      continue-error: false
