---
name: Validate and Release Terraform Module
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
      release-message:
        required: true
        type: string

jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main  
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-vsphere-vm
      terraform-version: 1.7.5
      tflint-version: v0.50.3
      continue-error: false

  release-terraform:
    name: Release
    needs: validate-terraform
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-terraform.yaml@main  
    with:
      module-name: vsphere-vm
      tag-name: "${{ github.event.inputs.release-tag }}"
      release-message: "${{ github.event.inputs.release-message }}"
      environment-name: k8s
      runs-on: arc-runner-scale-set-vsphere-vm
      continue-error: false
