---
name: Validate Terraform
on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
  pull_request:
    types: [opened, reopened]

jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main  
    with:
      environment-name: k8s
      runs-on: ghr-vsphere-vm-cicd
      terraform-version: 1.7.5
      tflint-version: v0.50.3
      continue-error: false
